### ISSUE TITLE
Couchpotato not using any tracker or indexer to search for movies

### ISSUE THREAD

**Issue by poplolnman** [RuudBurger/CouchPotatoServer#5596]
### Steps to reproduce:
1. Put in any credentials for any indexer or tracker
2. start search for any movie

### Information:
Movie(s) I have this with: ... any
Quality of the movie being searched: ...any
Providers I use: ...ptp, torrentday, iptorrents, i love torrents, hd4free, hd torrents, torrentbytes, omgwtfnzbs, cat.nzb, althub
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 05:13:08)
Running on: ...ubuntu-latest

### Logs:
```
10-16 22:01:29 ERROR [edia._base.providers.base] Failed to login PassThePopcorn: Traceback (most recent call last):
  File "/home/seeduser/.couchpotato/couchpotato/core/media/_base/providers/base.py", line 161, in login
    output = self.urlopen(self.urls['login'], data = self.getLoginParams())
  File "/home/seeduser/.couchpotato/couchpotato/core/plugins/base.py", line 220, in urlopen
    response = r.request(method, url, **kwargs)
  File "/home/seeduser/.couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/seeduser/.couchpotato/libs/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/home/seeduser/.couchpotato/libs/requests/adapters.py", line 371, in send
    timeout=timeout
  File "/home/seeduser/.couchpotato/libs/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/seeduser/.couchpotato/libs/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/seeduser/.couchpotato/libs/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/home/seeduser/.couchpotato/libs/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/home/seeduser/.couchpotato/libs/requests/packages/urllib3/contrib/pyopenssl.py", line 279, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
 
```

**Comment by CouchPotatoBot** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Fill in all the dots. They're there for a reason
- [x] Post logs, either inline (for smaller logs) or using [Pastebin](http://pastebin.com/)
- [x] Please wrap inline logs inside ``` for readability
- [ ] Enabled debug logging in Settings > Advanced (restart CP, be sure to disable after the bug is fixed)
- [x] Post full version information

Please make sure you also read [contribution guide](https://github.com/RuudBurger/CouchPotatoServer/blob/develop/contributing.md#issues) and followed all the steps. 
Make the title describe your issue. Having "CP not working" or "I get this bug" for 100 issues, isn't really helpful. My master will close issues if there isn't enough information. On a good day he will tag the issue on close with the reason (like `can't reproduce`), but usually he won't, the lazy asshat.

Sometimes my master seems like a grumpy cat and responds with short answers. This isn't (always) because he hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let him know. Maybe he can teach me his awesome ways.

Thanks!
